import 'dotenv/config';
import crypto from 'node:crypto';
import dns from 'node:dns/promises';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import express from 'express';
import Database from 'better-sqlite3';
import multer from 'multer';
import ExifReader from 'exifreader';
import PDFDocument from 'pdfkit';
import {demoCase, isSafeUrl, normalizeDomain} from '../src/core.js';

const here=path.dirname(fileURLToPath(import.meta.url)); const dataDir=path.join(here,'..','data'); const uploadDir=path.join(dataDir,'uploads'); fs.mkdirSync(dataDir,{recursive:true}); fs.mkdirSync(uploadDir,{recursive:true});
const db=new Database(path.join(dataDir,'truthtrace.db')); db.pragma('journal_mode = WAL');
db.exec('CREATE TABLE IF NOT EXISTS investigations (id TEXT PRIMARY KEY, payload TEXT NOT NULL, created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS provider_settings (name TEXT PRIMARY KEY, configured INTEGER NOT NULL, updated_at TEXT NOT NULL)');
const app=express(); app.use(express.json({limit:'1mb'})); app.use('/uploads',express.static(uploadDir,{fallthrough:false,maxAge:'7d'}));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024},fileFilter:(_,f,cb)=>cb(null,['image/jpeg','image/png','image/webp'].includes(f.mimetype))});
const providerNames=['search','factCheck','archive','reverseImage','llm'];
const configured=new Set(providerNames.filter(n=>process.env[`${n.replace(/[A-Z]/g,x=>`_${x}`).toUpperCase()}_API_KEY`]));
function saveCase(c){db.prepare('INSERT OR REPLACE INTO investigations(id,payload,created_at) VALUES (?,?,?)').run(c.id,JSON.stringify(c),c.createdAt)}
function readCase(id){const row=db.prepare('SELECT payload FROM investigations WHERE id=?').get(id);return row?JSON.parse(row.payload):null}
function listCases(){return db.prepare('SELECT payload FROM investigations ORDER BY created_at DESC').all().map(x=>JSON.parse(x.payload))}
if(!readCase('DEMO-001')) saveCase(demoCase());
function privateIp(ip){return ip==='::1'||ip.startsWith('fc')||ip.startsWith('fd')||/^(127\.|10\.|0\.|169\.254\.|192\.168\.|172\.(1[6-9]|2\d|3[0-1])\.)/.test(ip)}
async function safeTarget(value){if(!isSafeUrl(value)) throw new Error('Only public HTTP(S) URLs are allowed.');const u=new URL(value);const addresses=await dns.lookup(u.hostname,{all:true});if(!addresses.length||addresses.some(x=>privateIp(x.address))) throw new Error('Private or unresolved targets are not allowed.');return u}
function strip(html){return html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function meta(html,name){const m=html.match(new RegExp(`<meta[^>]+(?:name|property)=["']${name}["'][^>]+content=["']([^"']+)`, 'i'));return m?.[1]||''}
async function extractArticle(url){const target=await safeTarget(url);const control=new AbortController();const timer=setTimeout(()=>control.abort(),8000);try{const response=await fetch(target,{signal:control.signal,redirect:'error',headers:{'user-agent':'TRUTHTRACE/1.0 educational OSINT client'}});if(!response.ok)throw new Error(`Source returned HTTP ${response.status}`);const html=(await response.text()).slice(0,1_000_000);const title=meta(html,'og:title')||html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.trim()||target.hostname;return {title:strip(title),text:strip(html).slice(0,12000),domain:target.hostname,canonical:target.href};}finally{clearTimeout(timer)}}
async function generateSummary(title,text,claim){const fallback=`This investigation examines ${title||claim||'a submitted news item'}. It reviews the submitted content alongside source, claim, image and timeline signals; the assessment is an evidence indicator, not a declaration of truth.`;if(!process.env.LLM_API_KEY||!(text||claim))return {text:fallback,provider:'Local deterministic summary',status:'LOCAL'};const control=new AbortController();const timer=setTimeout(()=>control.abort(),9000);try{const prompt=`Summarize this news investigation in 2 concise neutral sentences. State what the item claims and what this OSINT review is used for. Do not decide true or false, invent facts, or mention this prompt. Title: ${title||'Not supplied'}\nClaim: ${claim||'Not supplied'}\nText: ${(text||'').slice(0,5500)}`;const r=await fetch('https://integrate.api.nvidia.com/v1/chat/completions',{method:'POST',signal:control.signal,headers:{Authorization:`Bearer ${process.env.LLM_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:'meta/llama-3.1-8b-instruct',messages:[{role:'user',content:prompt}],temperature:0.2,max_tokens:130})});if(!r.ok)throw new Error(`LLM returned ${r.status}`);const payload=await r.json();const value=payload?.choices?.[0]?.message?.content?.trim();if(!value)throw new Error('No LLM summary returned');return {text:value.slice(0,900),provider:'NVIDIA NIM',status:'AI-ASSISTED'};}catch{return {text:fallback,provider:'Local deterministic summary',status:'FALLBACK'};}finally{clearTimeout(timer)}}
function localFingerprint(buf){return crypto.createHash('sha256').update(buf).digest('hex').slice(0,32)}
app.get('/api/health',(_,res)=>res.json({ok:true,service:'truthtrace-api',database:'sqlite',providers:providerNames.map(name=>({name,configured:configured.has(name)}))}));
app.get('/api/investigations',(_,res)=>res.json({data:listCases()}));
app.get('/api/investigations/:id',(req,res)=>{const c=readCase(req.params.id);if(!c)return res.status(404).json({error:'Investigation not found'});res.json({data:c})});
app.put('/api/investigations/:id',(req,res)=>{const existing=readCase(req.params.id);if(!existing)return res.status(404).json({error:'Investigation not found'});const payload={...req.body,id:existing.id,createdAt:existing.createdAt};saveCase(payload);res.json({data:payload})});
app.post('/api/investigations',async(req,res)=>{const {url='',text='',headline='',claim='',domain=''}=req.body||{};if(!url&&!text&&!headline&&!claim&&!domain)return res.status(400).json({error:'Provide at least one investigation input.'});let article=null,warning='';if(url)try{article=await extractArticle(url)}catch(e){warning=e.message}const c=demoCase();c.id=`CASE-${crypto.randomUUID().slice(0,8).toUpperCase()}`;c.mode='LOCAL INVESTIGATION';c.createdAt=new Date().toISOString();c.title=headline||article?.title||claim||'Untitled investigation';c.target=url||'No remote URL provided';c.domain=domain||article?.domain||normalizeDomain(url)||'Not identified';c.status=warning?'Complete with extraction unavailable':'Complete';if(article){c.article={title:article.title,text:article.text,canonical:article.canonical};c.evidence.unshift({id:'E-000',type:'ARTICLE',title:'Article content extracted',description:`Retrieved ${article.text.length.toLocaleString()} characters from the submitted public URL.`,polarity:'NEUTRAL',source:c.domain,sourceUrl:article.canonical,observedAt:c.createdAt,confidence:100,reliability:'Observed',metadata:{provider:'Local extractor'}})}if(text){c.article={title:c.title,text:text.slice(0,12000)};c.evidence.unshift({id:'E-000',type:'ARTICLE',title:'Article text supplied',description:'Text was provided directly by the reviewer.',polarity:'NEUTRAL',source:'User input',sourceUrl:'',observedAt:c.createdAt,confidence:100,reliability:'Observed',metadata:{provider:'Local input'}})}c.summary=await generateSummary(c.title,c.article?.text,claim);if(warning)c.providerRuns=[{provider:'Article extractor',status:'UNAVAILABLE',message:warning}];saveCase(c);res.status(201).json({data:c,warning:warning||undefined})});
app.delete('/api/investigations/:id',(req,res)=>{db.prepare('DELETE FROM investigations WHERE id=?').run(req.params.id);res.status(204).end()});
app.post('/api/images/analyze',upload.single('image'),(req,res)=>{if(!req.file)return res.status(400).json({error:'A JPEG, PNG, or WebP image is required.'});const sha256=crypto.createHash('sha256').update(req.file.buffer).digest('hex');const extension={"image/jpeg":'.jpg',"image/png":'.png',"image/webp":'.webp'}[req.file.mimetype];const storedName=`${sha256.slice(0,24)}${extension}`;fs.writeFileSync(path.join(uploadDir,storedName),req.file.buffer);let tags={};try{tags=ExifReader.load(req.file.buffer)}catch{}const exif=Object.fromEntries(Object.entries(tags).filter(([k])=>['DateTime','Make','Model','GPSLatitude','GPSLongitude'].includes(k)).map(([k,v])=>[k,v.description||String(v.value)]));res.json({data:{name:req.file.originalname,type:req.file.mimetype,size:req.file.size,sha256,fingerprint:localFingerprint(req.file.buffer),previewUrl:`/uploads/${storedName}`,exif:Object.keys(exif).length?exif:null,reverseImage:{status:'UNAVAILABLE',message:'Reverse-image provider is not configured. Local fingerprint analysis completed.'}}})});
app.get('/api/settings/providers',(_,res)=>res.json({data:providerNames.map(name=>({name,configured:configured.has(name)}))}));
app.post('/api/settings/providers/:name',(req,res)=>{const {name}=req.params;if(!providerNames.includes(name))return res.status(404).json({error:'Unknown provider'});const hasKey=typeof req.body?.apiKey==='string'&&req.body.apiKey.length>8;if(hasKey)configured.add(name);else configured.delete(name);db.prepare('INSERT OR REPLACE INTO provider_settings(name,configured,updated_at) VALUES (?,?,?)').run(name,hasKey?1:0,new Date().toISOString());res.json({data:{name,configured:hasKey,note:'Key is held only in the running server process. Use .env for persistent configuration.'}})});
app.get('/api/reports/:id.pdf',(req,res)=>{const c=readCase(req.params.id);if(!c)return res.status(404).json({error:'Investigation not found'});res.set({'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="truthtrace-${c.id}.pdf"`});const pdf=new PDFDocument({margin:52,info:{Title:`TRUTHTRACE ${c.id}`,Author:'Aaditya Devadiga — OSINT Mini Project'}});pdf.pipe(res);const heading=t=>pdf.moveDown(.8).fontSize(15).fillColor('#103b47').text(t).moveDown(.35);const body=t=>pdf.fontSize(10.5).fillColor('#34424f').text(t,{lineGap:3});pdf.fontSize(21).fillColor('#103b47').text('TRUTHTRACE');pdf.fontSize(9).fillColor('#52707b').text(`OSINT MINI PROJECT · MADE BY AADITYA DEVADIGA · ${c.id}`);pdf.moveDown().fontSize(18).fillColor('#17212d').text('Investigation report');heading('Executive summary');body(c.summary?.text||`This investigation reviews ${c.title} through structured source, claim, image and timeline signals.`);heading('Investigation target');body(`Title: ${c.title}\nTarget: ${c.target}\nDomain: ${c.domain}\nCreated: ${c.createdAt}`);heading('Assessment');body(`${c.assessment.verdict} — ${c.assessment.score}/100 (${c.assessment.confidence} confidence; signal coverage ${c.assessment.coverage}). This is an evidence assessment, not a declaration of truth or falsity.`);heading('Score dimensions');for(const [name,value] of Object.entries(c.dimensions||{}))body(`${name.replace(/([A-Z])/g,' $1')}: ${value}/100`);pdf.addPage();heading('Evidence ledger');c.evidence.forEach(e=>{pdf.fontSize(10).fillColor('#17212d').text(`${e.id} · ${e.type} · ${e.polarity}`);body(`${e.title} — ${e.description}\nSource: ${e.source} · Observed: ${e.observedAt}`);pdf.moveDown(.35)});heading('Limitations and provenance');body('Provider availability and source limitations are recorded separately. Local image hashes, fingerprints and EXIF fields are technical observations, not proof of image origin. External search, archive, fact-check and reverse-image results must be verified against their cited source.');pdf.end()});
app.use((err,_,res,__)=>(err instanceof multer.MulterError?res.status(400).json({error:err.message}):res.status(500).json({error:'Unexpected server error'})));
app.listen(process.env.API_PORT||8787,()=>console.log(`TRUTHTRACE API listening on http://127.0.0.1:${process.env.API_PORT||8787}`));
