const root=document.querySelector('#app');
const api=async(path,options={})=>{const response=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'The local API request failed.');return payload};
function visibleId(){const text=root.querySelector('.report-title small,.case-meta')?.textContent||'';const found=text.match(/(?:CASE-[A-Z0-9-]+|LOCAL-001|DEMO-001)/)?.[0];return found==='LOCAL-001'?'DEMO-001':found}
async function submitInvestigation(event){const form=event.target;if(form.id!=='investigation-form')return;event.preventDefault();event.stopImmediatePropagation();const formData=new FormData(form);const url=formData.get('url').trim(),text=formData.get('text').trim(),headline=formData.get('headline').trim(),claim=formData.get('claim').trim(),domain=formData.get('domain').trim();if(!url&&!text&&!headline&&!claim&&!domain&&!formData.get('image')?.size){alert('Provide at least one investigation input.');return}try{form.querySelector('button[type="submit"]').disabled=true;form.querySelector('button[type="submit"]').textContent='Analysing locally…';const result=await api('/api/investigations',{method:'POST',body:JSON.stringify({url,text,headline,claim,domain})});const item=result.data;const image=formData.get('image');if(image?.size){const imageBody=new FormData();imageBody.append('image',image);const imageResponse=await fetch('/api/images/analyze',{method:'POST',body:imageBody});const imageResult=await imageResponse.json();if(!imageResponse.ok)throw new Error(imageResult.error||'Image analysis failed.');item.image={...item.image,...imageResult.data,reverse:imageResult.data.reverseImage.message};await api(`/api/investigations/${item.id}`,{method:'PUT',body:JSON.stringify(item)})}const cases=JSON.parse(localStorage.getItem('truthtrace-cases')||'[]').filter(c=>c.id!==item.id);cases.unshift(item);localStorage.setItem('truthtrace-cases',JSON.stringify(cases));location.hash=`/investigations/${item.id}`;location.reload()}catch(error){alert(error.message)}finally{const button=form.querySelector('button[type="submit"]');if(button){button.disabled=false;button.textContent='Create investigation →'}}}
async function providerPanel(){const settings=root.querySelector('.settings');if(!settings||settings.querySelector('.provider-config'))return;const card=document.createElement('article');card.className='provider-config';card.innerHTML='<h3>Provider keys</h3><p>Keys are sent only to your local backend and remain in memory for this session. Put replacements in <code>.env</code> for persistent use.</p><form><label>Provider <select name="provider"><option value="search">Search</option><option value="factCheck">Fact check</option><option value="archive">Archive</option><option value="reverseImage">Reverse image</option><option value="llm">AI claim extraction</option></select></label><label>API key <input name="apiKey" type="password" autocomplete="off" placeholder="Paste a replacement key locally"/></label><button class="ghost" type="submit">Save local provider</button></form><div class="provider-result">Checking local API…</div>';settings.append(card);try{const status=await api('/api/settings/providers');card.querySelector('.provider-result').textContent=status.data.map(p=>`${p.name}: ${p.configured?'configured':'unavailable'}`).join(' · ')}catch{card.querySelector('.provider-result').textContent='Local API unavailable. Run npm run dev.'}card.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{const r=await api(`/api/settings/providers/${f.get('provider')}`,{method:'POST',body:JSON.stringify({apiKey:f.get('apiKey')})});card.querySelector('.provider-result').textContent=`${r.data.name}: ${r.data.configured?'configured for this session':'unavailable'}`;e.target.reset()}catch(err){card.querySelector('.provider-result').textContent=err.message}}}
function pdfButton(){const report=root.querySelector('.report');if(!report||root.querySelector('[data-pdf]'))return;const id=visibleId();if(!id)return;const button=document.createElement('a');button.dataset.pdf='';button.className='ghost';button.href=`/api/reports/${id}.pdf`;button.textContent='Download PDF';root.querySelector('.page-head')?.append(button)}
async function refreshProviderStatus(){const settings=root.querySelector('.settings');if(!settings)return;try{const status=await api('/api/settings/providers');const labels={search:'Search provider',factCheck:'Fact-check provider',archive:'Archive provider',reverseImage:'Reverse image provider',llm:'AI claim extraction'};for(const provider of status.data){const label=labels[provider.name];const row=[...settings.querySelectorAll('article:first-child p')].find(p=>p.textContent.includes(label));if(row)row.innerHTML=`<span class="pill ${provider.configured?'good':''}">${provider.configured?'CONFIGURED':'UNAVAILABLE'}</span> ${label}`}}catch{/* Status panel is left unchanged if the local API is offline. */}}
document.addEventListener('submit',submitInvestigation,true);
document.addEventListener('submit',event=>{if(event.target.closest('.provider-config form'))setTimeout(refreshProviderStatus,250)},true);
new MutationObserver(()=>{providerPanel();pdfButton();refreshProviderStatus()}).observe(root,{childList:true,subtree:true});
