const root=document.querySelector('#app');
function enhanceGraph(graph){
  const nodes=[...graph.querySelectorAll('.node')];
  const evidence=nodes.filter(n=>n.dataset.evidence).map((n,index)=>({id:n.dataset.evidence,kind:[...n.classList].find(x=>['supporting','contradicting','neutral','unknown'].includes(x))||'neutral',index}));
  if(!evidence.length)return;
  const evidenceNodes=evidence.map((node,i)=>({...node,x:790,y:55+i*76}));
  const links=[`<line class="graph-link primary" x1="190" y1="265" x2="350" y2="125"/><line class="graph-link primary" x1="190" y1="265" x2="350" y2="360"/>`,...evidenceNodes.map((n,i)=>`<line class="graph-link ${n.kind}" x1="470" y1="${i%2?360:125}" x2="${n.x-72}" y2="${n.y}"/>`)].join('');
  graph.innerHTML=`<div class="graph-toolbar" role="toolbar" aria-label="Evidence graph controls"><button data-graph-control="zoom-in" aria-label="Zoom in">+</button><button data-graph-control="zoom-out" aria-label="Zoom out">−</button><button data-graph-control="fit" aria-label="Fit graph">⌗</button></div><div class="graph-viewport"><div class="graph-canvas"><svg class="graph-lines" viewBox="0 0 1000 520" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="graph-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z"/></marker></defs>${links}</svg><button class="graph-node article" style="--x:135px;--y:265px" data-graph-node="article">ARTICLE<span>Target</span></button><button class="graph-node claim" style="--x:410px;--y:125px" data-graph-node="C-02">C-02<span>Attendance claim</span></button><button class="graph-node claim" style="--x:410px;--y:360px" data-graph-node="C-03">C-03<span>Image claim</span></button>${evidenceNodes.map(n=>`<button class="graph-node ${n.kind}" style="--x:${n.x}px;--y:${n.y}px" data-evidence="${n.id}">${n.id}</button>`).join('')}</div></div><div class="graph-detail" aria-live="polite">Select a node to inspect its relationship in this investigation.</div><div class="graph-legend"><span><i class="article"></i> Target</span><span><i class="claim"></i> Claim</span><span><i class="supporting"></i> Supporting</span><span><i class="contradicting"></i> Contradicting</span><span><i class="neutral"></i> Neutral</span></div>`;
  graph.dataset.enhanced='true';let zoom=1;const canvas=graph.querySelector('.graph-canvas');const apply=()=>canvas.style.transform=`scale(${zoom})`;
  graph.querySelector('.graph-toolbar').onclick=e=>{const c=e.target.dataset.graphControl;if(c==='zoom-in')zoom=Math.min(1.35,zoom+.1);if(c==='zoom-out')zoom=Math.max(.7,zoom-.1);if(c==='fit')zoom=1;apply()};
  graph.querySelectorAll('.graph-node').forEach(node=>node.onclick=()=>{graph.querySelectorAll('.graph-node').forEach(x=>x.classList.remove('selected'));node.classList.add('selected');const id=node.dataset.evidence||node.dataset.graphNode;const kind=node.classList.contains('contradicting')?'contradicting':node.classList.contains('supporting')?'supporting':node.classList.contains('claim')?'claim':'target';graph.querySelector('.graph-detail').textContent=`${id}: ${kind} node. Connected lines show its case relationship.`});
}
function enhance(){root.querySelectorAll('.graph:not([data-enhanced])').forEach(enhanceGraph)}
new MutationObserver(enhance).observe(root,{childList:true,subtree:true});enhance();
